version: '3.8'

services:
  screenshoter:
    build: .
    container_name: tv-screenshoter
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    logging:
      driver: "none"
