services:
  screenshoter:
    build: .
    container_name: tv-screenshoter
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    logging:
      driver: "none"
