services:
  screenshoter:
    build: .
    container_name: tv-screenshoter
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    expose:
      - "3000"
    networks:
      - proxy
    logging:
      driver: "none"

networks:
  proxy:
    external: true
